Fixed urllib for python3
thetvdb/tvdb-v4-python pull request #4
Opened 2021-07-13 17:57 UTC by hrkrx

Removed unnecessary imports
Fixed method calls to urlencode

2021-07-31 06:50 UTC, PumpkinCheshire reviewed
From python 3.5, you still need to import urllib.request and urllib.parse or those modules will not be found.

2021-08-13 15:58 UTC, samwhipmedia approved these changes

2021-08-13 16:01 UTC, samwhipmedia commented
Sorry approved by accident, @hrkrx can you update to include import of urllib.request and urllib.parse?

2021-08-13 16:22 UTC, samwhipmedia requested changes
per comment, additional import needed.

2021-08-16 22:33 UTC, WayneD requested changes
I believe the  tags options changes aren't right.

2021-08-16 22:33 UTC, WayneD commented on tvdb_v4_official.py
> +        url = self.url.tag_options_url()
This shouldn't change the url function name, but instead it should pass the `id` arg:
```suggestion
        url = self.url.tag_option_url(id)
```

2021-08-16 22:33 UTC, WayneD commented on tvdb_v4_official.py
> +        url = self.url.tag_option_url(page)
This shouldn't change the url function name. Instead, the tag_options_url() function needs to accept a page arg. If you want to do something with the page arg, the url assignment in that function could also be changed, as in the second line of this suggested function:

```
   def tag_options_url(self, page=0):
        url = "{}/tags/options?page={}".format(self.base_url, page)
```

2021-08-29 04:29 UTC, WayneD commented on tvdb_v4_official.py
> -import urllib.request
When I tested with python 3.8.10 it still requires an "import urllib.request" for the script to work.

2021-09-01 16:32 UTC, closed without merging